# Serial params
port: "/dev/ttyUSB0"
baudrate: 230400
rate: 100

# Classification params
dataroot: "/home/frankie/catkin_ws/src/dataglove/bags"
resultroot: "/home/frankie/catkin_ws/src/dataglove/classification/results"
n_hid: 256
batch: 16
dt: 0.042
gamma: 2.7
epsilon: 4.7
gamma_range: 2.7
epsilon_range: 4.7
sron: true
mixron: true
liquidron: true
inp_scaling: 1.0
rho: 0.99
leaky: 1.0
use_test: true
trials: 1
topology: "full"  # choices: ["full", "ring", "band", "lower", "toeplitz", "orthogonal"]
sparsity: 0.0
reservoir_scaler: 1.0
threshold: 1
rc: 5.0
reset: 0.01
bias: 0.0
perc: 0.5
use_dvs: true
use_nmnist: true
